version: '3.8'

services:
  frontend:
    build:
      context: ./frontend/gef_analyzer-frontend/
      dockerfile: frontend.Dockerfile
    ports:
      - "3000:3000"
    command: npm run dev

  fastapi:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "8888:8111"
    command: python run_backend.py

  worker:
    depends_on:
      - fastapi
      - redis
    build:
      context: .
      dockerfile: backend.Dockerfile

    command: celery --app=backend.tasks.celery worker --loglevel=INFO

  flower:
    depends_on:
      - fastapi
      - redis
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "5555:5555"
    command: celery --app=backend.tasks.celery flower

  redis:
    image: redis:7
    ports:
      - "6379:6379"

#  rabbitmq:
#    image: rabbitmq
#    ports:
#      - "5672:5672"